export const USDC_ADDRESS = "0x3600000000000000000000000000000000000000" as const;

// The active deployment receives all new streams. The legacy address remains
// configured while its existing escrowed streams are still being settled.
export const PAYROLL_ADDRESS = (
  process.env.NEXT_PUBLIC_PAYROLL_ADDRESS ?? ""
) as `0x${string}`;
export const LEGACY_PAYROLL_ADDRESS = (
  process.env.NEXT_PUBLIC_LEGACY_PAYROLL_ADDRESS ?? ""
) as `0x${string}`;
export const PAYROLL_ADDRESSES = Array.from(
  new Set([PAYROLL_ADDRESS, LEGACY_PAYROLL_ADDRESS].filter(Boolean))
) as `0x${string}`[];

export const PAYROLL_ABI = [
  {
    type: "function",
    name: "adjudicator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "constructor",
    inputs: [
      { name: "_usdc", type: "address", internalType: "address" },
      { name: "_adjudicator", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStream",
    inputs: [
      { name: "employee", type: "address", internalType: "address" },
      { name: "ratePerSecond", type: "uint128", internalType: "uint128" },
      { name: "deposit", type: "uint128", internalType: "uint128" },
      { name: "invoiceRef", type: "string", internalType: "string" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStreams",
    inputs: [
      { name: "employees", type: "address[]", internalType: "address[]" },
      { name: "ratesPerSecond", type: "uint128[]", internalType: "uint128[]" },
      { name: "deposits", type: "uint128[]", internalType: "uint128[]" },
      { name: "invoiceRefs", type: "string[]", internalType: "string[]" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "streamIds", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStreamWithDeliverables",
    inputs: [
      { name: "employee", type: "address", internalType: "address" },
      { name: "ratePerSecond", type: "uint128", internalType: "uint128" },
      { name: "deposit", type: "uint128", internalType: "uint128" },
      { name: "invoiceRef", type: "string", internalType: "string" },
      { name: "streamDeliverables", type: "string", internalType: "string" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createStreamsWithDeliverables",
    inputs: [
      { name: "employees", type: "address[]", internalType: "address[]" },
      { name: "ratesPerSecond", type: "uint128[]", internalType: "uint128[]" },
      { name: "deposits", type: "uint128[]", internalType: "uint128[]" },
      { name: "invoiceRefs", type: "string[]", internalType: "string[]" },
      { name: "streamDeliverables", type: "string[]", internalType: "string[]" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "streamIds", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "topUp",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelStream",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requestCancellation",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "reason", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "appealCancellation",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "evidenceUri", type: "string", internalType: "string" },
      { name: "evidenceHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveCancellation",
    inputs: [
      { name: "streamId", type: "uint256", internalType: "uint256" },
      { name: "appealUpheld", type: "bool", internalType: "bool" },
      { name: "verdictHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeUnappealedCancellation",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeTimedOutAppeal",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancellationCaseId",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancellations",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "nonce", type: "uint64", internalType: "uint64" },
      { name: "requestedAt", type: "uint64", internalType: "uint64" },
      { name: "appealDeadline", type: "uint64", internalType: "uint64" },
      { name: "adjudicationDeadline", type: "uint64", internalType: "uint64" },
      { name: "escrowedRefund", type: "uint128", internalType: "uint128" },
      {
        name: "status",
        type: "uint8",
        internalType: "enum PayrollManager.CancellationStatus",
      },
      { name: "evidenceHash", type: "bytes32", internalType: "bytes32" },
      { name: "verdictHash", type: "bytes32", internalType: "bytes32" },
      { name: "reason", type: "string", internalType: "string" },
      { name: "evidenceUri", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "APPEAL_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ADJUDICATION_TIMEOUT",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "BANT_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bantDeadline",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deliverables",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "accrued",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "runway",
    inputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "streams",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "employer", type: "address", internalType: "address" },
      { name: "employee", type: "address", internalType: "address" },
      { name: "ratePerSecond", type: "uint128", internalType: "uint128" },
      { name: "startTime", type: "uint64", internalType: "uint64" },
      { name: "lastClaimTime", type: "uint64", internalType: "uint64" },
      { name: "deposit", type: "uint128", internalType: "uint128" },
      { name: "totalDeposited", type: "uint128", internalType: "uint128" },
      { name: "withdrawn", type: "uint128", internalType: "uint128" },
      { name: "active", type: "bool", internalType: "bool" },
      { name: "invoiceRef", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEmployerStreams",
    inputs: [{ name: "employer", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEmployeeStreams",
    inputs: [{ name: "employee", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextStreamId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "StreamCreated",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "employee", type: "address", indexed: true },
      { name: "ratePerSecond", type: "uint128", indexed: false },
      { name: "deposit", type: "uint128", indexed: false },
      { name: "invoiceRef", type: "string", indexed: false },
      { name: "startTime", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "employee", type: "address", indexed: true },
      { name: "amount", type: "uint128", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StreamToppedUp",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "amount", type: "uint128", indexed: false },
    ],
  },
  {
    type: "event",
    name: "StreamDeliverablesSet",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "deliverables", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CancellationRequested",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "nonce", type: "uint64", indexed: true },
      { name: "employer", type: "address", indexed: true },
      { name: "accruedPaid", type: "uint128", indexed: false },
      { name: "escrowedRefund", type: "uint128", indexed: false },
      { name: "appealDeadline", type: "uint64", indexed: false },
      { name: "caseId", type: "bytes32", indexed: false },
      { name: "reason", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CancellationAppealed",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "nonce", type: "uint64", indexed: true },
      { name: "employee", type: "address", indexed: true },
      { name: "caseId", type: "bytes32", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "evidenceUri", type: "string", indexed: false },
      { name: "adjudicationDeadline", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CancellationResolved",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "nonce", type: "uint64", indexed: true },
      { name: "caseId", type: "bytes32", indexed: true },
      { name: "appealUpheld", type: "bool", indexed: false },
      { name: "refunded", type: "uint128", indexed: false },
      { name: "verdictHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "CancellationFinalized",
    inputs: [
      { name: "streamId", type: "uint256", indexed: true },
      { name: "nonce", type: "uint64", indexed: true },
      {
        name: "status",
        type: "uint8",
        indexed: false,
        internalType: "enum PayrollManager.CancellationStatus",
      },
      { name: "refunded", type: "uint128", indexed: false },
    ],
  },
  // ---- Stream requests + negotiation ----
  {
    type: "function",
    name: "requestStream",
    inputs: [
      { name: "payer", type: "address", internalType: "address" },
      { name: "ratePerSecond", type: "uint128", internalType: "uint128" },
      { name: "deposit", type: "uint128", internalType: "uint128" },
      { name: "invoiceRef", type: "string", internalType: "string" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptRequest",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "counterRequest",
    inputs: [
      { name: "requestId", type: "uint256", internalType: "uint256" },
      { name: "newRate", type: "uint128", internalType: "uint128" },
      { name: "newDeposit", type: "uint128", internalType: "uint128" },
      { name: "newStartAt", type: "uint64", internalType: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptCounter",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "streamId", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectCounter",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "reclaimExpiredCounter",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rejectRequest",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelRequest",
    inputs: [{ name: "requestId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "requests",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "payee", type: "address", internalType: "address" },
      { name: "payer", type: "address", internalType: "address" },
      { name: "ratePerSecond", type: "uint128", internalType: "uint128" },
      { name: "deposit", type: "uint128", internalType: "uint128" },
      { name: "startAt", type: "uint64", internalType: "uint64" },
      { name: "counterDeadline", type: "uint64", internalType: "uint64" },
      { name: "status", type: "uint8", internalType: "enum PayrollManager.ReqStatus" },
      { name: "invoiceRef", type: "string", internalType: "string" },
      { name: "streamId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPayerRequests",
    inputs: [{ name: "payer", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPayeeRequests",
    inputs: [{ name: "payee", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextRequestId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "COUNTER_WINDOW",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RequestCreated",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "payee", type: "address", indexed: true },
      { name: "payer", type: "address", indexed: true },
      { name: "ratePerSecond", type: "uint128", indexed: false },
      { name: "deposit", type: "uint128", indexed: false },
      { name: "startAt", type: "uint64", indexed: false },
      { name: "invoiceRef", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RequestCountered",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "ratePerSecond", type: "uint128", indexed: false },
      { name: "deposit", type: "uint128", indexed: false },
      { name: "startAt", type: "uint64", indexed: false },
      { name: "counterDeadline", type: "uint64", indexed: false },
    ],
  },
  {
    type: "event",
    name: "RequestAccepted",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "streamId", type: "uint256", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RequestRejected",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "by", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RequestCancelled",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "by", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RequestExpired",
    inputs: [
      { name: "requestId", type: "uint256", indexed: true },
      { name: "refunded", type: "uint128", indexed: false },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
] as const;
